### ISSUE TITLE
Support deployment to existing namespaces

### ISSUE THREAD

**Issue by jewzaam** [openshift/osd-operators-registry#21]
Specifically `openshift-monitoring` for `configure-alertmanager-operator`.  The NS already has an `OperatorGroup`, the CSV will fail because it cannot pick one, both match.

**Comment by jewzaam** [comment]
Desired behavior..

For an operator, if the namespace already has an OperatorGroup in it of a different name:

- do not deploy a new operator
- make sure the operator's CSV will match the existing OperatorGroup

This may need to be driven down into the individual operator.  Have a default CSV template and operator manifest template.  If the operator provides an override use that instead.  Alternately could have something output by `make env` that indicated the support modes required for the operator group, if a new operator group should be created, and if a new namespace should be created.

Probably should merge https://github.com/openshift/osd-operators-registry/issues/22 into this?

**Comment by lisa** [comment]
@jewzaam 

> For an operator, if the namespace already has an OperatorGroup in it of a different name

* do not deploy a new operator
* make sure the operator's CSV will match the existing OperatorGroup

Is this a behaviour of OLM? It still sounds like there needs to be logic somewhere, and I'm not sure if it exists already or needs to be created someplace.

**Comment by jewzaam** [comment]
Probably easiest to make this repo dumb and pull in whatever the individual operator tells it to pull in.  Then there's no logic, the bundled operators specify templates and where to get them from `make env`.  And while we're at it add in ability to override the `manifests/` dir.. will be coming probably soon.

So:

1. `make env` gives the location of manifests dir, csv template (optional), and operator template (optional)
2. `make manifests` targets use this to set where manifests are pulled from, the csv template used, and operator template used

**Comment by lisa** [comment]
@jewzaam Let's chat tomorrow on this.
