### ISSUE TITLE
Support customizations to CSV per operator

### ISSUE THREAD

**Issue by jewzaam** [openshift/osd-operators-registry#23]
To deploy configure-alertmanager-operator I had to edit the CSV to set  MultiNamespace true so it's deployable in openshift-monitoring NS.  Otherwise OLM cannot find an OperatorGroup match.  We cannot deploy two OperatorGroups, see https://github.com/openshift/osd-operators-registry/issues/22

**Comment by lisa** [comment]
This is a duplicate of #22. See also #25 and #21.
