### ISSUE TITLE
Generate SelectorSyncSet per operator

### ISSUE THREAD

**Issue by jewzaam** [openshift/osd-operators-registry#4]
At least gives a starting point for deployment to a Hive cluster.  It should target any ClusterDeployment with label `managed=true`.

**Comment by lisa** [comment]
@jewzaam is this to facilitate the deployment of the subscription and catalogsource objects?

**Comment by jewzaam** [comment]
Yes, a starting point or maybe all the selectorsyncsets deployed to hive could be generated, removing human error.

**Comment by jewzaam** [comment]
Done in https://github.com/openshift/osd-operators-registry/pull/17
