### ISSUE TITLE
Builds depend on version but cause version to change.

### ISSUE THREAD

**Issue by jewzaam** [openshift/osd-operators-registry#7]
The version of the image is based on the git hash.  But there are manifests and catalog-manifests that are generated as a side effect.  Therefore, version is not easy to manage.

I propose version is set based on a hash of what is in the image:  `catalog-manifests/`

If anything in that changes it's a new version, period.  If anything else changes, it doesn't matter.  It won't be in the released artifact.

@lisa @rogbas interested in what your thoughts.

**Comment by lisa** [comment]
This is one of the things that informed my suggestion for [CalVer](https://calver.org/) over git commit numbers.

A workaround is to pin to the commit count and sha that is from the checkout and don't count the manifest changes towards it.

**Comment by rogbas** [comment]
+1 on using a md5 hash of what's in `catalog-manifests/` only. 

The rest of this repo shouldn't matter to img tagging, like if I push a new README, or change something in `manifests/`, it's not going to regenerate an img and update the img tag in `00-catalog.yaml`

That way the only changes that matter are the ones that will change the final outcome of `catalog-manifests`, like updating rules in the Makefile, the gen CSV python script, or changing templates on `templates/` 

On that note, we could add the md5 hash as a git commit comment via Makefile for future reference.

**Comment by jewzaam** [comment]
For this particular repo it's a problem because we generate source that gets committed. For operators the thing generated is the image, which isn't committed.  The point of having commit # and git hash is to get back to the source that generated that image.  We could move to tags in git.

1. generate catalog-manifests
2. create md5sum from catalog-manifests to use in version (now branch-md5sum)
3. generate manifests
4. git commit
5. tag with branch-md5sum (aka version)
6. git push w/ tags
7. docker build & push

**Comment by jewzaam** [comment]
Going to fix this today.  I went to deploy dedicated-admin-operator and the image for this repo wasn't out there.  I can't easily figure out which checkout I need and what to do at that checkout.  Builds are not idempotent.

**Comment by jewzaam** [comment]
While I'm on it.. having the date in the version will mean if we run build for the catalog and nothing changes except the date we'll get a new version of the operator images.  This will mean we do not have an image for that operator anymore.

**Comment by jewzaam** [comment]
https://github.com/openshift/dedicated-admin-operator/issues/28

**Comment by jewzaam** [comment]
https://github.com/openshift/osd-operators-registry/pull/10 for a tag on this repo
